export const CAR_DATA = [
    {
      id: "1",
      name: "VW Golf 6",
      price: "37",
      model: "Golf 6",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
    {
      id: "2",
      name: "Audi A1 S-Line",
      price: "45",
      model: "Audi",
      mark: "A1",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Gasoline",
    },
  
    {
      id: "3",
      name: "Toyota Camry",
      price: "30",
      model: "Camry",
      mark: "Toyota",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Hybrid",
    },
  
    {
      id: "4",
      name: "BMW 320 ModernLine",
      price: "35",
      model: "320",
      mark: "BMW",
      year: "2012",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  
    {
      id: "5",
      name: "Mercedes-Benz GLK",
      price: "50",
      model: "Benz GLK",
      mark: "Mercedes",
      year: "2006",
      doors: "4/5",
      air: "Yes",
      transmission: "Manual",
      fuel: "Diesel",
    },
  
    {
      id: "6",
      name: "VW Passat CC",
      price: "25",
      model: "Passat CC",
      mark: "Volkswagen",
      year: "2008",
      doors: "4/5",
      air: "Yes",
      transmission: "Automatic",
      fuel: "Gasoline",
    },
];
